theme: jekyll-theme-architect

title: [javaserverfaces-spec]
description: [JavaServer(TM) Faces Specification]

# sidebar links url
links:
  source: https://github.com/javaserverfaces/mojarra
  #download:
  mailinglist: https://javaee.groups.io/g/jsf-spec/topics
  #javadocs:
  #docs:
  #faq:
  #hide_issuetracker: true #set explicitly to 'true' if you don't want to have the issue tracker link displayed

